import { getAssetFromKV } from '@cloudflare/kv-asset-handler'
// @ts-expect-error — generated by wrangler at build time
import manifestJSON from '__STATIC_CONTENT_MANIFEST'

const assetManifest = JSON.parse(manifestJSON)

export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response> {
    try {
      return await getAssetFromKV(
        { request, waitUntil: ctx.waitUntil.bind(ctx) },
        {
          ASSET_NAMESPACE: env.__STATIC_CONTENT as KVNamespace,
          ASSET_MANIFEST: assetManifest,
        }
      )
    } catch {
      return new Response('Not found', { status: 404 })
    }
  },
}
